# custom loss functions for TimeSeries Prediction
# base code generated by Perplexity AI
import keras.ops as K



def mase_loss_multi_step(y_true, y_pred):
    # Assuming y_true and y_pred are of shape (batch_size, 64, features)
    n = K.shape(y_true)[1]  # number of time steps (64)
    
    # Calculate naive forecast (persistence model)
    # We use the last known value to predict all 64 future values
    #naive_forecast = K.repeat_elements(y_true[:, :1, :], n, axis=1)
    naive_forecast = K.repeat(y_true[:, :1, :], n, axis=1)
    
    # Calculate mean absolute error of naive forecast
    mae_naive = K.mean(K.abs(y_true - naive_forecast), axis=(1, 2))
    
    # Calculate mean absolute error of our model's forecast
    mae_forecast = K.mean(K.abs(y_true - y_pred), axis=(1, 2))
    
    # MASE is the ratio of model's MAE to naive forecast's MAE
    mase = mae_forecast / (mae_naive + 1e-8)  # add a small value to avoid division by zero
    
    return K.mean(mase)  # Return scalar


def trace_mse_loss(y_true, y_pred):
    # Assuming y_true and y_pred are of shape (batch_size, forecast_horizon, features)
    forecast_horizon = K.shape(y_true)[1]
    
    def mse_h(h):
        # Calculate MSE for horizon h
        y_true_h = y_true[:, :h, :]
        y_pred_h = y_pred[:, :h, :]
        return K.mean(K.square(y_true_h - y_pred_h))
    
    # Sum MSE for all horizons
    tmse = K.sum([mse_h(h) for h in range(1, forecast_horizon + 1)])
    
    return tmse